# NumPy exercises

In [2]:
#import the Numpy package
import numpy as np

In [3]:
#Set the random seed
np.random.seed(859)

In [5]:
#Create a random array of 100 values between 0 and 1
arr_1 = np.random.rand(100)

#Display the resulting array
arr_1

array([0.15700854, 0.41080809, 0.98507234, 0.3801485 , 0.33949913,
       0.21982355, 0.2931561 , 0.41817129, 0.14498206, 0.02424045,
       0.00920897, 0.33717002, 0.05197823, 0.9150345 , 0.92046476,
       0.42083261, 0.97857695, 0.24257692, 0.29083097, 0.48834308,
       0.57374361, 0.90344002, 0.2951836 , 0.0562096 , 0.24817813,
       0.93343119, 0.02332197, 0.73828503, 0.23900878, 0.60235213,
       0.1819568 , 0.35610882, 0.72831219, 0.21508016, 0.80068247,
       0.17679207, 0.40265315, 0.12841897, 0.33216432, 0.01726349,
       0.08326946, 0.28808968, 0.41045931, 0.11091862, 0.75661554,
       0.90401755, 0.81256798, 0.57781609, 0.60326138, 0.70112676,
       0.0707155 , 0.94056194, 0.46971289, 0.84167641, 0.44773881,
       0.41299915, 0.93992695, 0.16517926, 0.28406607, 0.85071314,
       0.30394712, 0.25039873, 0.88321642, 0.58485085, 0.73664309,
       0.21862636, 0.47401317, 0.42029544, 0.58658383, 0.45716522,
       0.69006102, 0.8402728 , 0.43641648, 0.59148953, 0.49324

In [6]:
#Report the shape of the resulting array
arr_1.shape

(100,)

In [7]:
#Report the data type of the resulting array
arr_1.dtype

dtype('float64')

In [8]:
#Remote the mean value of all values in your array
arr_1.mean()

0.4634853558185105

In [10]:
#Multiply each value in your array to get values between 0 and 100, saving the results as "arr_2"
arr_2 = arr_1 *100
arr_2

array([15.70085351, 41.08080907, 98.5072337 , 38.01485018, 33.94991333,
       21.98235481, 29.31561034, 41.81712905, 14.49820635,  2.42404494,
        0.9208974 , 33.71700192,  5.19782254, 91.50344957, 92.04647632,
       42.08326126, 97.85769525, 24.25769189, 29.08309652, 48.83430761,
       57.37436142, 90.34400161, 29.51835984,  5.62095955, 24.81781327,
       93.34311897,  2.33219733, 73.82850294, 23.90087809, 60.2352134 ,
       18.19568026, 35.61088234, 72.83121856, 21.50801631, 80.06824714,
       17.6792072 , 40.26531496, 12.84189664, 33.21643239,  1.72634874,
        8.32694647, 28.80896802, 41.04593123, 11.09186215, 75.66155389,
       90.40175505, 81.25679833, 57.78160922, 60.32613761, 70.1126764 ,
        7.07154991, 94.05619356, 46.9712894 , 84.16764075, 44.77388061,
       41.29991452, 93.99269514, 16.51792627, 28.40660663, 85.07131387,
       30.39471239, 25.03987286, 88.32164187, 58.48508496, 73.66430886,
       21.86263577, 47.4013166 , 42.02954394, 58.65838253, 45.71

In [11]:
#Reshape the array above to be 25 rows and 4 columns, saving the result as "arr_3"
arr_3 = arr_2.reshape(25,4)
arr_3

array([[15.70085351, 41.08080907, 98.5072337 , 38.01485018],
       [33.94991333, 21.98235481, 29.31561034, 41.81712905],
       [14.49820635,  2.42404494,  0.9208974 , 33.71700192],
       [ 5.19782254, 91.50344957, 92.04647632, 42.08326126],
       [97.85769525, 24.25769189, 29.08309652, 48.83430761],
       [57.37436142, 90.34400161, 29.51835984,  5.62095955],
       [24.81781327, 93.34311897,  2.33219733, 73.82850294],
       [23.90087809, 60.2352134 , 18.19568026, 35.61088234],
       [72.83121856, 21.50801631, 80.06824714, 17.6792072 ],
       [40.26531496, 12.84189664, 33.21643239,  1.72634874],
       [ 8.32694647, 28.80896802, 41.04593123, 11.09186215],
       [75.66155389, 90.40175505, 81.25679833, 57.78160922],
       [60.32613761, 70.1126764 ,  7.07154991, 94.05619356],
       [46.9712894 , 84.16764075, 44.77388061, 41.29991452],
       [93.99269514, 16.51792627, 28.40660663, 85.07131387],
       [30.39471239, 25.03987286, 88.32164187, 58.48508496],
       [73.66430886, 21.

In [12]:
#Show the 3rd row of this array
arr_3[2,]

array([14.49820635,  2.42404494,  0.9208974 , 33.71700192])

In [15]:
#Show the values in the 2nd column of this array
arr_3[:,1]

array([41.08080907, 21.98235481,  2.42404494, 91.50344957, 24.25769189,
       90.34400161, 93.34311897, 60.2352134 , 21.50801631, 12.84189664,
       28.80896802, 90.40175505, 70.1126764 , 84.16764075, 16.51792627,
       25.03987286, 21.86263577, 45.7165216 , 59.14895307, 46.40193053,
        3.90217904, 19.95579676, 47.677797  , 32.04392201, 23.65277294])

In [17]:
#Show the mean of the values in the 2nd column
arr_3[:,1].mean()

42.99727781187444